version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed-microservice
    depends_on:
      - postgres
    networks:
      - api-network
    ports:
      - ${PORT}:3000
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - api-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  api-network:

volumes:
  db:
